### PR TITLE
feat: update Nospz to 20230216

### PR DESCRIPTION
**Pull request by Honoka55**
It‘s about updating NospzGothicMoe to version 20230215:

1. Updated the NospzGothicMoe font to the 20230215 version, which includes over fifty new characters. You can find a detailed changelog [here](https://github.com/Honoka55/Nospz/tree/master/Moe#changelog).
2. Changed the font format from ttf to woff2, which reduces the font size by 40%. Please enable the upload of woff2 file on Moegirl Commons, upload the new font file and update the `url` in MediaWiki:Gadget-GothicMoe.css to the direct link of Commons on merging.
3. Please update [the associated abuse filter](https://zh.moegirl.org.cn/Special:AbuseFilter/74). The new code is available [here](https://github.com/Honoka55/Nospz/blob/master/Moe/Abuse), which will ensure that the characters already included in the font will not trigger the abuse filter, making it easier to maintain for future updates. ~~In fact, when reviewing the abuse logs, most edits were related to Karin Isobe.~~

Please feel free to contact me directly if you have any questions or concerns. Thank you for considering my changes.

### CODE REVIEW

**Comment by AnnAngela** [comment]
明天来，还是用图站好，jsdelivr在内地还是不太好用

**Comment by Honoka55** [comment]
> 明天来，还是用图站好，jsdelivr在内地还是不太好用

需要共享站开一下woff2上传，合并时把链接替换掉。另外发现一点问题，稍后会更新一下

**Comment by lovelyCARDINAL** [comment]
为啥过滤器不直接写Unicode啊……写文字基本上看不到

**Comment by Honoka55** [comment]
> 为啥过滤器不直接写Unicode啊……写文字基本上看不到 @Honoka55

@lovelyCARDINAL 可以查一下当年的[讨论记录](https://zh.moegirl.org.cn/萌娘百科_talk:讨论版/技术实现/存档/2020年09月#申请增加一个过滤器及两个标签)，我记得是写Unicode报错才有人提出写文字的

**Comment by lovelyCARDINAL** [comment]
可以用啊，当年用的方法不对。
请参考滥用过滤器137的写法。

**Comment by Honoka55** [comment]
那可以相应改写一下，结果上应该无差异

**Comment by lovelyCARDINAL** [comment]
确实，但是更直观。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by AnnAngela** [comment]
运维终于弄好上传限制了，现在上传好了，地址： https://img.moegirl.org.cn/common/7/77/NospzGothicMoe_20230216.woff2

**Review by AnnAngela — APPROVED** [review]
LGTM

**Pull request merged**
