### PR TITLE
提出{{胡话}}的内联CSS

### PR DESCRIPTION
**Pull request by gui-ying233**
RT，在同步更新后记得删除模板内的内联CSS。

### CODE REVIEW

**Comment by lovelyCARDINAL** [comment]
过2天提醒我一下删除内联CSS吧？感觉立即删除不太好

**Comment by AmeroHan** [comment]
胡话的`<s>`需要改成`<del>`吗

**Comment by lovelyCARDINAL** [comment]
s和del有什么区别来着

**Comment by AmeroHan** [comment]
> s和del有什么区别来着

`<s>` represents things that are no longer relevant or no longer accurate.

`<del>` represents a range of text that has been deleted from a document.

`<s>`对胡话好像也说得过去？

**Comment by lovelyCARDINAL** [comment]
del不能对多行应用

**Pull request merged**
